package brickbreaker.vista;

import brickbreaker.controlador.Control;
import brickbreaker.modelo.Barra;
import brickbreaker.modelo.Pelota;

public class JpNiveles extends javax.swing.JPanel {
     private static Control control;
     private int nivelSeleccionado;
    
    public JpNiveles() {
        
        initComponents();
    }

    
    public static void setControl(Control control){
        JpNiveles.control = control;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnRegresar1 = new javax.swing.JButton();
        btnNivel3 = new javax.swing.JButton();
        btnNivel1 = new javax.swing.JButton();
        btnNivel2 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresar1.setBackground(new java.awt.Color(0, 0, 0));
        btnRegresar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/boton-close.png"))); // NOI18N
        btnRegresar1.setBorderPainted(false);
        btnRegresar1.setFocusPainted(false);
        btnRegresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 150, 50));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(696, 0, 200, 600));

        btnNivel3.setText("Nivel 3");
        btnNivel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNivel3ActionPerformed(evt);
            }
        });
        add(btnNivel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 170, 70));

        btnNivel1.setText("Nivel 1");
        btnNivel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNivel1ActionPerformed(evt);
            }
        });
        add(btnNivel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 170, 70));

        btnNivel2.setText("Nivel 2");
        btnNivel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNivel2ActionPerformed(evt);
            }
        });
        add(btnNivel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 170, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar1ActionPerformed
        JpInicio jpInicio = new JpInicio();
        Control.cambiarPanel(jpInicio);
    }//GEN-LAST:event_btnRegresar1ActionPerformed

    private void btnNivel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNivel3ActionPerformed
        nivelSeleccionado = 3;  // Asigna el nivel 3
        JpJuego.setNivelSeleccionado(nivelSeleccionado);
        control.setNivelSeleccionado(nivelSeleccionado);  // Informa al Control el nivel seleccionado
        control.reiniciarJuego();  // Reinicia el juego para actualizar los bloques según el nivel
        Control.cambiarPanel(Control.getJpJuego());
    }//GEN-LAST:event_btnNivel3ActionPerformed

    private void btnNivel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNivel1ActionPerformed
        nivelSeleccionado = 1;  // Asigna el nivel 1
    control.setNivelSeleccionado(nivelSeleccionado);  // Informa al Control el nivel seleccionado
    control.reiniciarJuego();  // Reinicia el juego para actualizar los bloques según el nivel
    Control.cambiarPanel(Control.getJpJuego());
    }//GEN-LAST:event_btnNivel1ActionPerformed

    private void btnNivel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNivel2ActionPerformed
        nivelSeleccionado = 2;  // Asigna el nivel 2
    control.setNivelSeleccionado(nivelSeleccionado);  // Informa al Control el nivel seleccionado
    control.reiniciarJuego();  // Reinicia el juego para actualizar los bloques según el nivel
    Control.cambiarPanel(Control.getJpJuego());

    }//GEN-LAST:event_btnNivel2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNivel1;
    private javax.swing.JButton btnNivel2;
    private javax.swing.JButton btnNivel3;
    private javax.swing.JButton btnRegresar1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
